import { useCallback, useEffect, useMemo, useState } from 'react';
import { ApiError, entityApi } from '@/api';
import { BuildingIcon, ChevronLeftIcon, EditIcon, LayersIcon, PlusIcon, RefreshIcon, ReportsIcon, SearchIcon, SlidersIcon, TrashIcon, UsersIcon } from '@/components/icons';
import { Alert, Badge, Button, ConfirmDialog, EmptyState, LoadingState, Select, TextInput } from '@/components/ui';
import { useAuth, useEntities, useToast } from '@/hooks';
import type { EntityBook, EntityBranch, EntityGstin, ReportingEntity } from '@/types';
import { isAdministratorRole } from '@/types';
import { formatDateTime, toTitleCase } from '@/utils/formatters';
import { CreateEntityModal } from './CreateEntityModal';
import { BookDrawer, BranchDrawer, GstinDrawer } from './EntityChildDrawers';
import { GroupsPanel } from './GroupsPanel';
import './EntitiesSection.css';

type DetailTab = 'overview' | 'branches' | 'gstins' | 'books';
type EntityNavigationTab = 'groups' | DetailTab;
type PendingAction = { kind: 'entity' | 'branch' | 'gstin' | 'book'; id: string; label: string; active?: boolean } | null;
type EntityConfigurationSummary = { branches: EntityBranch[]; gstins: EntityGstin[]; books: EntityBook[] };
const PAGE_SIZE = 8;

function StatusBadge({ active }: { active: boolean }) { return <Badge tone={active ? 'success' : 'neutral'}>{active ? 'Active' : 'Inactive'}</Badge>; }

export function EntitiesSection() {
  const { user } = useAuth(); const { entities, selectedEntity, status, errorMessage, reload } = useEntities(); const toast = useToast();
  const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [ascending, setAscending] = useState(true); const [page, setPage] = useState(1);
  const [selectedId, setSelectedId] = useState<string | null>(null); const [detailTab, setDetailTab] = useState<DetailTab>('overview'); const [emptyConfigurationTab, setEmptyConfigurationTab] = useState<Exclude<DetailTab, 'overview'> | null>(null); const [emptyBranchCreateOpen, setEmptyBranchCreateOpen] = useState(false); const [emptyGstinCreateOpen, setEmptyGstinCreateOpen] = useState(false); const [emptyBookCreateOpen, setEmptyBookCreateOpen] = useState(false); const [showGroups, setShowGroups] = useState(false); const [groupRefreshKey, setGroupRefreshKey] = useState(0); const [groupCreateOpen, setGroupCreateOpen] = useState(false); const [editor, setEditor] = useState<ReportingEntity | null | undefined>(undefined); const [pending, setPending] = useState<PendingAction>(null); const [working, setWorking] = useState(false);
  const [configurationByEntity, setConfigurationByEntity] = useState<Record<string, EntityConfigurationSummary>>({});
  const isAdmin = isAdministratorRole(user?.role);
  const filtered = useMemo(() => entities.filter((entity) => {
    const term = query.trim().toLowerCase(); return (!term || entity.name.toLowerCase().includes(term) || (entity.code ?? '').toLowerCase().includes(term) || (entity.pan ?? '').toLowerCase().includes(term)) && (!statusFilter || String(entity.active) === statusFilter);
  }).sort((a,b) => (ascending ? 1 : -1) * a.name.localeCompare(b.name)), [ascending, entities, query, statusFilter]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const rows = filtered.slice((Math.min(page,pages)-1)*PAGE_SIZE, Math.min(page,pages)*PAGE_SIZE);
  const selected = entities.find((entity) => entity.id === selectedId) ?? null;
  const openEntity = (entityId: string, tab: DetailTab = 'overview') => { setEmptyConfigurationTab(null); setDetailTab(tab); setSelectedId(entityId); };

  useEffect(() => {
    let current = true;
    if (entities.length === 0) return () => { current = false; };
    void Promise.all(entities.map(async (entity) => {
      const [branches, gstins, books] = await Promise.all([entityApi.listBranches(entity.id), entityApi.listGstins(entity.id), entityApi.listBooks(entity.id)]);
      return [entity.id, { branches, gstins, books }] as const;
    })).then((entries) => { if (current) setConfigurationByEntity(Object.fromEntries(entries)); }).catch(() => { if (current) setConfigurationByEntity({}); });
    return () => { current = false; };
  }, [entities]);

  const editorSaved = (saved: ReportingEntity) => { setEditor(undefined); if (emptyConfigurationTab) { setDetailTab(emptyConfigurationTab); setEmptyConfigurationTab(null); setSelectedId(saved.id); } else setSelectedId((current) => current ? saved.id : current); toast.success(saved.createdAt === saved.updatedAt ? 'Entity created successfully.' : 'Changes saved successfully.'); void reload(); };
  const confirmEntityAction = () => { if (!pending || pending.kind !== 'entity') return; setWorking(true); const request = pending.active === undefined ? entityApi.remove(pending.id) : entityApi.setStatus(pending.id, pending.active);
    void request.then(() => { toast.success(pending.active === undefined ? 'Entity archived successfully.' : `Entity ${pending.active ? 'activated' : 'deactivated'} successfully.`); if (pending.active === undefined) setSelectedId(null); setPending(null); return reload(); }).catch((reason: unknown) => toast.error(reason instanceof ApiError ? reason.message : 'Unable to update entity.')).finally(() => setWorking(false)); };

  if (selected) return <EntityDetails key={selected.id} entity={selected} entities={entities} initialTab={detailTab} isAdmin={isAdmin} onSelectEntity={(entityId, tab) => { setDetailTab(tab); setSelectedId(entityId); }} onOpenGroups={() => { setSelectedId(null); setDetailTab('overview'); setShowGroups(true); }} onBack={() => { setSelectedId(null); setDetailTab('overview'); }} onEdit={() => setEditor(selected)} entityEditor={<CreateEntityModal key={editor === undefined ? 'entity-editor-closed' : editor?.id ?? 'new-entity'} isOpen={editor !== undefined} entity={editor ?? null} onClose={() => setEditor(undefined)} onSaved={editorSaved} />} />;

  return <div className="entities-section">
    <div className="entities-heading"><div><h2>{showGroups ? 'Groups' : emptyConfigurationTab ? (emptyConfigurationTab === 'gstins' ? 'GSTINs' : toTitleCase(emptyConfigurationTab)) : 'Entities'}</h2><p>{showGroups ? 'Organize related entities into business groups.' : emptyConfigurationTab ? `Manage ${emptyConfigurationTab === 'gstins' ? 'GSTINs' : emptyConfigurationTab} belonging to an entity.` : 'Manage companies and their accounting configurations.'}</p></div></div>
    <EntityNavigation active={showGroups ? 'groups' : emptyConfigurationTab ?? 'overview'} onSelect={(tab) => { if (tab === 'groups') { setEmptyConfigurationTab(null); setShowGroups(true); return; } setShowGroups(false); if (tab === 'overview') { setEmptyConfigurationTab(null); return; } const targetEntity = selectedEntity ?? entities[0]; if (targetEntity) openEntity(targetEntity.id, tab); else setEmptyConfigurationTab(tab); }} onRefresh={() => { if (showGroups) setGroupRefreshKey((value) => value + 1); else void reload(); }} refreshing={!showGroups && status === 'loading'} onCreate={showGroups ? () => setGroupCreateOpen(true) : emptyConfigurationTab === 'branches' ? () => setEmptyBranchCreateOpen(true) : emptyConfigurationTab === 'gstins' ? () => setEmptyGstinCreateOpen(true) : emptyConfigurationTab === 'books' ? () => setEmptyBookCreateOpen(true) : () => setEditor(null)} createLabel={showGroups ? 'Create Group' : emptyConfigurationTab === 'branches' ? 'Create Branch' : emptyConfigurationTab === 'gstins' ? 'Create GSTIN' : emptyConfigurationTab === 'books' ? 'Create Book' : 'Create Entity'} />
    {showGroups ? <GroupsPanel refreshKey={groupRefreshKey} createOpen={groupCreateOpen} entities={entities} onRequestCreate={() => setGroupCreateOpen(true)} onCloseCreate={() => setGroupCreateOpen(false)} /> : emptyConfigurationTab ? <div className="entities-card"><div className="entities-padding"><EmptyState icon={<BuildingIcon size={25} />} title={`No entity available for ${emptyConfigurationTab === 'gstins' ? 'GSTINs' : emptyConfigurationTab}`} description={emptyConfigurationTab === 'branches' ? 'You can open the Create Branch window now. Create an entity before saving the branch.' : emptyConfigurationTab === 'gstins' ? 'You can open the Create GSTIN window now. Create an entity before saving the GSTIN.' : emptyConfigurationTab === 'books' ? 'You can open the Create Book window now. Create an entity before saving the book.' : 'Create an entity first. Its configuration section will open automatically after creation.'} action={<Button leadingIcon={<PlusIcon />} onClick={() => { if (emptyConfigurationTab === 'branches') setEmptyBranchCreateOpen(true); else if (emptyConfigurationTab === 'gstins') setEmptyGstinCreateOpen(true); else if (emptyConfigurationTab === 'books') setEmptyBookCreateOpen(true); else setEditor(null); }}>{emptyConfigurationTab === 'branches' ? 'Create Branch' : emptyConfigurationTab === 'gstins' ? 'Create GSTIN' : emptyConfigurationTab === 'books' ? 'Create Book' : 'Create Entity'}</Button>} /></div></div> : <div className="entities-card">
      <div className="entities-toolbar"><div className="entities-toolbar__search"><TextInput id="entity-search-settings" type="search" placeholder="Search this table" leadingIcon={<SearchIcon />} value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /></div><Select id="entity-status-filter" aria-label="Filter by status" options={[{value:'',label:'All statuses'},{value:'true',label:'Active'},{value:'false',label:'Inactive'}]} value={statusFilter} onValueChange={(status) => { setStatusFilter(status); setPage(1); }} /><span className="management-table-tools__count">{filtered.length} / {entities.length}</span><Button size="sm" variant="secondary" leadingIcon={<SlidersIcon />}>Preferences</Button></div>
      {status === 'loading' && <EntityListSkeleton />}{status === 'error' && <div className="entities-padding"><Alert variant="danger">{errorMessage ?? 'Unable to load entities.'}</Alert></div>}
      {status === 'ready' && rows.length === 0 ? <div className="entities-padding"><EmptyState icon={<BuildingIcon size={25} />} title={query || statusFilter ? 'No matching entities' : 'No entities configured'} description={query || statusFilter ? 'Try a different search or status filter.' : 'Create the first company to begin configuring branches, GSTINs and books.'} action={!query && !statusFilter ? <Button leadingIcon={<PlusIcon />} onClick={() => setEditor(null)}>Create Entity</Button> : undefined} /></div> : status === 'ready' && <>
        <div className="entity-table-wrap"><table className="entity-table entity-table--wide"><thead><tr><th><button type="button" className="table-sort" onClick={() => setAscending((value) => !value)}>Entity {ascending ? '↑' : '↓'}</button></th><th>Group</th><th>PAN</th><th>Code</th><th>Primary Branch</th><th>Mode</th><th>Related</th><th>Tally Endpoint</th><th>Actions</th></tr></thead><tbody>{rows.map((entity) => { const configuration = configurationByEntity[entity.id]; const primaryBranch = configuration?.branches.find((branch) => branch.primaryBranch); return <tr key={entity.id} onClick={() => openEntity(entity.id)}><td data-label="Entity"><div className="entity-name-cell"><span><BuildingIcon size={17} /></span><div><strong>{entity.name}</strong><small>{entity.description || entity.name}</small></div></div></td><td data-label="Group">{entity.groupName || '—'}</td><td data-label="PAN">{entity.pan || '—'}</td><td data-label="Code"><code>{entity.code || '—'}</code></td><td data-label="Primary Branch">{primaryBranch?.name || '—'}</td><td data-label="Mode">{entity.multipleBranches ? 'Multi-branch' : 'Single-branch'}</td><td data-label="Related"><div className="related-counts" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => openEntity(entity.id, 'branches')}>{configuration?.branches.length ?? 0} Branches</button><button type="button" onClick={() => openEntity(entity.id, 'gstins')}>{configuration?.gstins.length ?? 0} GSTINs</button><button type="button" onClick={() => openEntity(entity.id, 'books')}>{configuration?.books.length ?? 0} Books</button></div></td><td data-label="Tally Endpoint">{entity.tallyHost || 'localhost'}:{entity.tallyPort || 9000}</td><td className="entity-actions" data-label="Actions" onClick={(event) => event.stopPropagation()}><RowActions canDelete={isAdmin} onEdit={() => setEditor(entity)} onDelete={() => setPending({kind:'entity',id:entity.id,label:entity.name})} /></td></tr>; })}</tbody></table></div>
        <div className="entities-pagination"><span>{filtered.length} {filtered.length === 1 ? 'entity' : 'entities'}</span><div><Button size="sm" variant="secondary" disabled={page<=1} onClick={() => setPage((value) => value-1)}>Previous</Button><span>Page {Math.min(page,pages)} of {pages}</span><Button size="sm" variant="secondary" disabled={page>=pages} onClick={() => setPage((value) => value+1)}>Next</Button></div></div>
      </>}
    </div>}
    <CreateEntityModal key={editor === undefined ? 'entity-editor-closed' : editor?.id ?? 'new-entity'} isOpen={editor !== undefined} entity={editor ?? null} onClose={() => setEditor(undefined)} onSaved={editorSaved} />
    <BranchDrawer key={emptyBranchCreateOpen ? 'empty-create-branch-open' : 'empty-create-branch-closed'} entityId="" isOpen={emptyBranchCreateOpen} branch={null} onClose={() => setEmptyBranchCreateOpen(false)} onSaved={() => undefined} />
    <GstinDrawer key={emptyGstinCreateOpen ? 'empty-create-gstin-open' : 'empty-create-gstin-closed'} entityId="" entityName="" branches={[]} isOpen={emptyGstinCreateOpen} gstin={null} onClose={() => setEmptyGstinCreateOpen(false)} onSaved={() => undefined} />
    {emptyBookCreateOpen && <BookDrawer key="empty-create-book" entityId="" isOpen book={null} books={[]} onClose={() => setEmptyBookCreateOpen(false)} onSaved={() => undefined} />}
    <ConfirmDialog isOpen={pending !== null} title={pending?.active === undefined ? `Archive ${pending?.label ?? 'entity'}?` : `${pending?.active ? 'Activate' : 'Deactivate'} ${pending?.label ?? 'entity'}?`} message={pending?.active === undefined ? 'The record and its historical relationships will be preserved, but it will leave active management lists.' : 'The record stays available for history and can be changed again later.'} confirmLabel={pending?.active === undefined ? 'Archive' : pending?.active ? 'Activate' : 'Deactivate'} isDestructive={pending?.active !== true} isConfirming={working} onConfirm={confirmEntityAction} onCancel={() => setPending(null)} />
  </div>;
}

const entityNavigationItems: { value: EntityNavigationTab; label: string; icon: React.ReactNode }[] = [
  { value: 'groups', label: 'Groups', icon: <UsersIcon /> },
  { value: 'overview', label: 'Entities', icon: <BuildingIcon /> },
  { value: 'branches', label: 'Branches', icon: <LayersIcon /> },
  { value: 'gstins', label: 'GSTINs', icon: <SlidersIcon /> },
  { value: 'books', label: 'Books', icon: <ReportsIcon /> },
];

function EntityNavigation({ active, onSelect, onRefresh, refreshing = false, onCreate, createLabel = 'Create Entity' }: { active: EntityNavigationTab; onSelect: (tab: EntityNavigationTab) => void; onRefresh: () => void; refreshing?: boolean; onCreate?: (() => void) | undefined; createLabel?: string }) {
  return <div className="entity-navigation">
    <nav className="entity-navigation__tabs" aria-label="Entity management">
      {entityNavigationItems.map((item) => <button key={item.value} type="button" className={active === item.value ? 'entity-navigation__tab entity-navigation__tab--active' : 'entity-navigation__tab'} aria-current={active === item.value ? 'page' : undefined} onClick={() => onSelect(item.value)}>{item.icon}<span>{item.label}</span></button>)}
    </nav>
    <div className="entity-navigation__actions">
      <Button size="sm" variant="secondary" leadingIcon={<RefreshIcon />} disabled={refreshing} onClick={onRefresh}>{refreshing ? 'Refreshing…' : 'Refresh'}</Button>
      {onCreate && <Button size="sm" leadingIcon={<PlusIcon />} onClick={onCreate}>{createLabel}</Button>}
    </div>
  </div>;
}

function RowActions({ canDelete, onEdit, onDelete }: { canDelete: boolean; onEdit: () => void; onDelete: () => void }) {
  return <div className="row-actions"><button type="button" aria-label="Edit" title="Edit" onClick={onEdit}><EditIcon size={16} /></button><button type="button" aria-label={canDelete ? 'Delete' : 'Only administrators can delete'} title={canDelete ? 'Delete' : 'Only administrators can delete'} disabled={!canDelete} onClick={onDelete}><TrashIcon size={16} /></button></div>;
}

interface DetailsProps { entity: ReportingEntity; entities: ReportingEntity[]; initialTab: DetailTab; isAdmin: boolean; onSelectEntity: (entityId: string, tab: DetailTab) => void; onOpenGroups: () => void; onBack: () => void; onEdit: () => void; entityEditor: React.ReactNode; }
function EntityDetails({ entity, entities, initialTab, isAdmin, onSelectEntity, onOpenGroups, onBack, onEdit, entityEditor }: DetailsProps) {
  const toast = useToast(); const [tab, setTab] = useState<DetailTab>(initialTab); const [branches, setBranches] = useState<EntityBranch[] | null>(null); const [gstins, setGstins] = useState<EntityGstin[] | null>(null); const [books, setBooks] = useState<EntityBook[] | null>(null); const [loadError, setLoadError] = useState<string | null>(null);
  const [branchEditor, setBranchEditor] = useState<EntityBranch | null | undefined>(); const [gstinEditor, setGstinEditor] = useState<EntityGstin | null | undefined>(); const [bookEditor, setBookEditor] = useState<EntityBook | null | undefined>(); const [pending, setPending] = useState<PendingAction>(null); const [working, setWorking] = useState(false);
  const loadChildren = useCallback(() => Promise.all([entityApi.listBranches(entity.id), entityApi.listGstins(entity.id), entityApi.listBooks(entity.id)]).then(([nextBranches,nextGstins,nextBooks]) => { setBranches(nextBranches); setGstins(nextGstins); setBooks(nextBooks); setLoadError(null); }).catch((reason: unknown) => setLoadError(reason instanceof ApiError ? reason.message : 'Unable to load entity configuration.')), [entity.id]);
  useEffect(() => { void loadChildren(); }, [loadChildren]);
  const childSaved = (message: string) => { toast.success(message); void loadChildren(); };
  const confirmChildAction = () => { if (!pending || pending.kind === 'entity') return; setWorking(true); const archive = pending.active === undefined; let request: Promise<unknown>;
    if (pending.kind === 'branch') request = archive ? entityApi.archiveBranch(entity.id,pending.id) : entityApi.setBranchStatus(entity.id,pending.id,pending.active!);
    else if (pending.kind === 'gstin') request = archive ? entityApi.archiveGstin(entity.id,pending.id) : entityApi.setGstinStatus(entity.id,pending.id,pending.active!);
    else request = archive ? entityApi.archiveBook(entity.id,pending.id) : entityApi.setBookStatus(entity.id,pending.id,pending.active!);
    void request.then(() => { toast.success(archive ? 'Record archived successfully.' : 'Status updated successfully.'); setPending(null); return loadChildren(); }).catch((reason: unknown) => toast.error(reason instanceof ApiError ? reason.message : 'Unable to update record.')).finally(() => setWorking(false)); };
  const features = [['Multiple Branches',entity.multipleBranches],['e-Invoice',entity.eInvoiceEnabled],['e-Way Bill',entity.eWayBillEnabled],['Stock',entity.stockEnabled],['Cost Centre Extraction',entity.costCentreExtractionEnabled]] as const;
  return <div className="entity-details">
    <button type="button" className="entity-back" onClick={onBack}><ChevronLeftIcon /> Entities</button>
    <header className="entity-detail-header"><div className="entity-detail-header__identity"><span>{entity.code?.slice(0,2)}</span><div><div className="entity-detail-header__title"><h2>{entity.name}</h2><StatusBadge active={entity.active} /></div><p>Entity Code: <code>{entity.code}</code></p></div></div><Button variant="secondary" leadingIcon={<EditIcon />} onClick={onEdit}>Edit Entity</Button></header>
    <EntityNavigation active={tab} onSelect={(nextTab) => { if (nextTab === 'groups') onOpenGroups(); else if (nextTab === 'overview') onBack(); else setTab(nextTab); }} onRefresh={() => void loadChildren()} refreshing={branches === null || gstins === null || books === null} onCreate={tab !== 'overview' ? () => { if (tab === 'branches') setBranchEditor(null); else if (tab === 'gstins') setGstinEditor(null); else setBookEditor(null); } : undefined} createLabel={tab === 'branches' ? 'Create Branch' : tab === 'gstins' ? 'Add GSTIN' : tab === 'books' ? 'Add Book' : 'Create Entity'} />
    {tab !== 'overview' && <div className="entity-context"><Select id="configuration-entity" aria-label="Select entity" options={entities.map((item) => ({ value: item.id, label: `${item.name}${item.tallyCompanyName ? ` (${item.tallyCompanyName})` : ''}` }))} value={entity.id} onValueChange={(entityId) => onSelectEntity(entityId, tab)} />{tab === 'branches' && <p>Entity: <strong>{entity.name}</strong> | Current Primary: <strong>{branches?.find((branch) => branch.primaryBranch)?.name || 'Not set'}</strong></p>}</div>}
    {loadError && <Alert variant="danger">{loadError}</Alert>}
    {tab === 'overview' && <section className="entity-overview"><div className="entity-overview__top"><div><h3>Entity Overview</h3><p>Legal identity, accounting connection and enabled capabilities.</p></div></div><dl className="management-detail-grid"><Detail label="Entity Name" value={entity.name}/><Detail label="Entity Code" value={entity.code}/><Detail label="PAN" value={entity.pan}/><Detail label="Primary GSTIN" value={entity.primaryGstin}/><Detail label="GSTIN Username" value={entity.gstnUsername}/><Detail label="GSTIN Password" value={entity.gstnPasswordConfigured ? 'Configured securely' : 'Not configured'}/><Detail label="Tally Company" value={entity.tallyCompanyName}/><Detail label="Tally Host" value={entity.tallyHost}/><Detail label="Tally Port" value={String(entity.tallyPort)}/><Detail label="Status" value={entity.active?'Active':'Inactive'}/><Detail label="Created On" value={formatDateTime(entity.createdAt)}/><Detail label="Updated On" value={formatDateTime(entity.updatedAt)}/></dl><div className="feature-summary"><h3>Business Features</h3><div>{features.map(([label,enabled]) => <span key={label} className={enabled?'feature-summary__enabled':''}>{label}<b>{enabled?'On':'Off'}</b></span>)}</div></div></section>}
    {tab === 'branches' && <BranchTable items={branches} isAdmin={isAdmin} onEdit={setBranchEditor} onArchive={(item) => setPending({kind:'branch',id:item.id,label:item.name})} />}
    {tab === 'gstins' && <GstinTable items={gstins} entityName={entity.name} entityPan={entity.pan} isAdmin={isAdmin} onEdit={setGstinEditor} onArchive={(item) => setPending({kind:'gstin',id:item.id,label:item.gstin})} />}
    {tab === 'books' && <BookTable items={books} isAdmin={isAdmin} onEdit={setBookEditor} onArchive={(item) => setPending({kind:'book',id:item.id,label:item.name})} />}
    {entityEditor}
    <BranchDrawer key={branchEditor === undefined ? 'branch-editor-closed' : branchEditor?.id ?? 'new-branch'} entityId={entity.id} isOpen={branchEditor !== undefined} branch={branchEditor ?? null} onClose={() => setBranchEditor(undefined)} onSaved={() => childSaved(branchEditor ? 'Changes saved successfully.' : 'Branch added successfully.')} />
    <GstinDrawer key={gstinEditor === undefined ? 'gstin-editor-closed' : gstinEditor?.id ?? 'new-gstin'} entityId={entity.id} entityName={entity.name} branches={branches ?? []} isOpen={gstinEditor !== undefined} gstin={gstinEditor ?? null} onClose={() => setGstinEditor(undefined)} onSaved={() => childSaved(gstinEditor ? 'Changes saved successfully.' : 'GSTIN added successfully.')} />
    {bookEditor !== undefined && <BookDrawer key={bookEditor?.id ?? 'new-book'} entityId={entity.id} isOpen book={bookEditor ?? null} books={books ?? []} onClose={() => setBookEditor(undefined)} onSaved={() => childSaved(bookEditor ? 'Changes saved successfully.' : 'Book connected successfully.')} />}
    <ConfirmDialog isOpen={pending !== null} title={pending?.active === undefined ? `Archive ${pending?.label ?? 'record'}?` : `${pending?.active ? 'Activate' : 'Deactivate'} ${pending?.label ?? 'record'}?`} message="Historical relationships will be preserved. This action can be reversed where appropriate." confirmLabel={pending?.active === undefined?'Archive':pending?.active?'Activate':'Deactivate'} isDestructive={pending?.active !== true} isConfirming={working} onConfirm={confirmChildAction} onCancel={() => setPending(null)} />
  </div>;
}

function Detail({ label, value }: { label: string; value: string | null }) { return <div><dt>{label}</dt><dd>{value || '—'}</dd></div>; }
function EntityListSkeleton() { return <div className="entity-skeleton" aria-label="Loading entities" aria-busy="true">{Array.from({ length: 5 }, (_, index) => <div key={index}><span/><span/><span/><span/></div>)}</div>; }

function TableTools({ query, onQuery, visible, total }: { query: string; onQuery: (value: string) => void; visible: number; total: number }) {
  return <div className="management-table-tools"><div className="management-table-tools__search"><TextInput id="management-table-search" type="search" aria-label="Search this table" placeholder="Search this table" leadingIcon={<SearchIcon />} value={query} onChange={(event) => onQuery(event.target.value)} /></div><span className="management-table-tools__count">{visible} / {total}</span><Button size="sm" variant="secondary" leadingIcon={<SlidersIcon />}>Preferences</Button></div>;
}

function BranchTable({ items, isAdmin, onEdit, onArchive }: { items: EntityBranch[] | null; isAdmin: boolean; onEdit: (item: EntityBranch) => void; onArchive: (item: EntityBranch) => void }) {
  const [query, setQuery] = useState(''); const term = query.trim().toLowerCase(); const visible = (items ?? []).filter((item) => !term || item.name.toLowerCase().includes(term) || item.code.toLowerCase().includes(term)).sort((first, second) => Number(second.primaryBranch) - Number(first.primaryBranch));
  return <section className="child-panel"><TableTools query={query} onQuery={setQuery} visible={visible.length} total={items?.length ?? 0} />{items === null ? <LoadingState message="Loading branches…" /> : visible.length === 0 ? <EmptyState icon={<LayersIcon />} title={items.length ? 'No matching branches' : 'No branches added'} description={items.length ? 'Try a different search.' : 'Add branches belonging to this entity.'} /> : <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Branch Name</th><th>Code</th><th>Primary</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{item.name}</td><td><code>{item.code || '—'}</code></td><td>{item.primaryBranch ? <Badge tone="accent">Primary</Badge> : '—'}</td><td><StatusBadge active={item.active} /></td><td className="management-table__actions"><RowActions canDelete={isAdmin} onEdit={() => onEdit(item)} onDelete={() => onArchive(item)} /></td></tr>)}</tbody></table></div>}</section>;
}

function GstinTable({ items, entityName, entityPan, isAdmin, onEdit, onArchive }: { items: EntityGstin[] | null; entityName: string; entityPan: string | null; isAdmin: boolean; onEdit: (item: EntityGstin) => void; onArchive: (item: EntityGstin) => void }) {
  const [query, setQuery] = useState(''); const term = query.trim().toLowerCase(); const visible = (items ?? []).filter((item) => !term || item.gstin.toLowerCase().includes(term) || item.stateName.toLowerCase().includes(term) || (item.gstnUsername ?? '').toLowerCase().includes(term) || (item.linkedBranchName ?? '').toLowerCase().includes(term) || (item.linkedBookName ?? '').toLowerCase().includes(term));
  return <section className="child-panel"><TableTools query={query} onQuery={setQuery} visible={visible.length} total={items?.length ?? 0} />{items === null ? <LoadingState message="Loading GSTINs…" /> : visible.length === 0 ? <EmptyState icon={<SlidersIcon />} title={items.length ? 'No matching GSTINs' : 'No GSTINs configured'} description={items.length ? 'Try a different search.' : 'Add the GST registrations applicable to this entity.'} /> : <div className="management-table-wrap"><table className="management-table management-table--gstin"><thead><tr><th>GSTIN</th><th>PAN</th><th>State</th><th>Registration Type</th><th>Linked Book</th><th>GSTN Username</th><th>GSTN Password</th><th>E-Invoice</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((item) => { const isDraft = item.gstin.startsWith('DRAFT-'); const linkedContext = item.linkedBranchName ? `${entityName} — ${item.linkedBranchName}` : item.linkedBookName || entityName; return <tr key={item.id}><td><code>{item.gstin}</code></td><td>{!isDraft ? item.gstin.slice(2, 12) : entityPan || '—'}</td><td>{!isDraft ? item.gstin.slice(0, 2) : item.stateName || '—'}</td><td>{toTitleCase(item.registrationType)}</td><td>{linkedContext}</td><td>{item.gstnUsername || '—'}</td><td>{item.passwordConfigured ? 'Set' : 'Not Set'}</td><td>{item.eInvoiceApplicable ? 'Applicable' : 'Not applicable'}</td><td><StatusBadge active={item.active} /></td><td className="management-table__actions"><RowActions canDelete={isAdmin} onEdit={() => onEdit(item)} onDelete={() => onArchive(item)} /></td></tr>; })}</tbody></table></div>}</section>;
}

function BookTable({ items, isAdmin, onEdit, onArchive }: { items: EntityBook[] | null; isAdmin: boolean; onEdit: (item: EntityBook) => void; onArchive: (item: EntityBook) => void }) {
  const [query, setQuery] = useState(''); const term = query.trim().toLowerCase(); const visible = (items ?? []).filter((item) => !term || item.name.toLowerCase().includes(term) || item.source.toLowerCase().includes(term) || (item.tallyCompanyName ?? '').toLowerCase().includes(term) || (item.organizationName ?? '').toLowerCase().includes(term));
  return <section className="child-panel"><TableTools query={query} onQuery={setQuery} visible={visible.length} total={items?.length ?? 0} />{items === null ? <LoadingState message="Loading books…" /> : visible.length === 0 ? <EmptyState icon={<ReportsIcon />} title={items.length ? 'No matching books' : 'No books connected'} description={items.length ? 'Try a different search.' : 'Connect a Tally or Zoho Books source.'} /> : <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Book Name</th><th>Source</th><th>Details</th><th>Primary</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{item.name}</td><td><Badge tone="neutral">{item.source === 'TALLY' ? 'Tally' : 'Zoho Books'}</Badge></td><td><div className="book-details-cell"><span>{item.source === 'TALLY' ? item.tallyCompanyName || 'Tally connection' : item.organizationName || 'Zoho Books connection'}</span><small>{item.source === 'TALLY' ? `${item.tallyHost || 'localhost'}:${item.tallyPort || 9000}` : item.accountsDomain || (item.tokenConnected ? 'Token connected' : 'Not connected')}</small></div></td><td>{item.primaryBook ? 'Yes' : 'No'}</td><td><StatusBadge active={item.active} /></td><td className="management-table__actions"><RowActions canDelete={isAdmin} onEdit={() => onEdit(item)} onDelete={() => onArchive(item)} /></td></tr>)}</tbody></table></div>}</section>;
}
