spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.bjkouoejgamqybwagnwh&password=Gouthami%2Ejchpl%40150
    username: postgres.bjkouoejgamqybwagnwh
    password: Gouthami%2Ejchpl%40150
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  security:
    detailed-authentication-errors: true

logging:
  level:
    com.customreporting: DEBUG
    org.hibernate.SQL: INFO