spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${PORT:10000}

app:
  cors:
    allowed-origins:
      - https://custom-reporting-frontend.vercel.app
      - https://custom-reporting-frontend-35xai1iny-gouthamijchpl-webs-projects.vercel.app